/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/_painel'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PainelAtrasosRouteImport } from './routes/_painel.atrasos'
import { Route as PainelCadastrosRouteImport } from './routes/_painel.cadastros'
import { Route as PainelComprasRouteImport } from './routes/_painel.compras'
import { Route as PainelConfiguracoesRouteImport } from './routes/_painel.configuracoes'
import { Route as PainelDashboardRouteImport } from './routes/_painel.dashboard'
import { Route as PainelEnvaseRouteImport } from './routes/_painel.envase'
import { Route as PainelEstoqueRouteImport } from './routes/_painel.estoque'
import { Route as PainelManutencaoRouteImport } from './routes/_painel.manutencao'
import { Route as PainelPerdasRouteImport } from './routes/_painel.perdas'
import { Route as PainelRelatoriosRouteImport } from './routes/_painel.relatorios'
import { Route as PainelSemAcessoRouteImport } from './routes/_painel.sem-acesso'
import { Route as PainelPedidosIndexRouteImport } from './routes/_painel.pedidos.index'
import { Route as PainelPedidosIdRouteImport } from './routes/_painel.pedidos.$id'
import { Route as PainelProducaoIndexRouteImport } from './routes/_painel.producao.index'
import { Route as PainelProducaoIdRouteImport } from './routes/_painel.producao.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/_painel',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAtrasosRoute = PainelAtrasosRouteImport.update({
  id: '/atrasos',
  path: '/atrasos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCadastrosRoute = PainelCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => PainelRoute,
} as any)
const PainelComprasRoute = PainelComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDashboardRoute = PainelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEnvaseRoute = PainelEnvaseRouteImport.update({
  id: '/envase',
  path: '/envase',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEstoqueRoute = PainelEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => PainelRoute,
} as any)
const PainelManutencaoRoute = PainelManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPerdasRoute = PainelPerdasRouteImport.update({
  id: '/perdas',
  path: '/perdas',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRelatoriosRoute = PainelRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSemAcessoRoute = PainelSemAcessoRouteImport.update({
  id: '/sem-acesso',
  path: '/sem-acesso',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPedidosIndexRoute = PainelPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPedidosIdRoute = PainelPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => PainelRoute,
} as any)
const PainelProducaoIndexRoute = PainelProducaoIndexRouteImport.update({
  id: '/producao/',
  path: '/producao/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelProducaoIdRoute = PainelProducaoIdRouteImport.update({
  id: '/producao/$id',
  path: '/producao/$id',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/atrasos': typeof PainelAtrasosRoute
  '/cadastros': typeof PainelCadastrosRoute
  '/compras': typeof PainelComprasRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/envase': typeof PainelEnvaseRoute
  '/estoque': typeof PainelEstoqueRoute
  '/manutencao': typeof PainelManutencaoRoute
  '/perdas': typeof PainelPerdasRoute
  '/relatorios': typeof PainelRelatoriosRoute
  '/sem-acesso': typeof PainelSemAcessoRoute
  '/pedidos/$id': typeof PainelPedidosIdRoute
  '/producao/$id': typeof PainelProducaoIdRoute
  '/pedidos/': typeof PainelPedidosIndexRoute
  '/producao/': typeof PainelProducaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/atrasos': typeof PainelAtrasosRoute
  '/cadastros': typeof PainelCadastrosRoute
  '/compras': typeof PainelComprasRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/envase': typeof PainelEnvaseRoute
  '/estoque': typeof PainelEstoqueRoute
  '/manutencao': typeof PainelManutencaoRoute
  '/perdas': typeof PainelPerdasRoute
  '/relatorios': typeof PainelRelatoriosRoute
  '/sem-acesso': typeof PainelSemAcessoRoute
  '/pedidos/$id': typeof PainelPedidosIdRoute
  '/producao/$id': typeof PainelProducaoIdRoute
  '/pedidos': typeof PainelPedidosIndexRoute
  '/producao': typeof PainelProducaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_painel': typeof PainelRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_painel/atrasos': typeof PainelAtrasosRoute
  '/_painel/cadastros': typeof PainelCadastrosRoute
  '/_painel/compras': typeof PainelComprasRoute
  '/_painel/configuracoes': typeof PainelConfiguracoesRoute
  '/_painel/dashboard': typeof PainelDashboardRoute
  '/_painel/envase': typeof PainelEnvaseRoute
  '/_painel/estoque': typeof PainelEstoqueRoute
  '/_painel/manutencao': typeof PainelManutencaoRoute
  '/_painel/perdas': typeof PainelPerdasRoute
  '/_painel/relatorios': typeof PainelRelatoriosRoute
  '/_painel/sem-acesso': typeof PainelSemAcessoRoute
  '/_painel/pedidos/$id': typeof PainelPedidosIdRoute
  '/_painel/producao/$id': typeof PainelProducaoIdRoute
  '/_painel/pedidos/': typeof PainelPedidosIndexRoute
  '/_painel/producao/': typeof PainelProducaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/atrasos'
    | '/cadastros'
    | '/compras'
    | '/configuracoes'
    | '/dashboard'
    | '/envase'
    | '/estoque'
    | '/manutencao'
    | '/perdas'
    | '/relatorios'
    | '/sem-acesso'
    | '/pedidos/$id'
    | '/producao/$id'
    | '/pedidos/'
    | '/producao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/atrasos'
    | '/cadastros'
    | '/compras'
    | '/configuracoes'
    | '/dashboard'
    | '/envase'
    | '/estoque'
    | '/manutencao'
    | '/perdas'
    | '/relatorios'
    | '/sem-acesso'
    | '/pedidos/$id'
    | '/producao/$id'
    | '/pedidos'
    | '/producao'
  id:
    | '__root__'
    | '/'
    | '/_painel'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/_painel/atrasos'
    | '/_painel/cadastros'
    | '/_painel/compras'
    | '/_painel/configuracoes'
    | '/_painel/dashboard'
    | '/_painel/envase'
    | '/_painel/estoque'
    | '/_painel/manutencao'
    | '/_painel/perdas'
    | '/_painel/relatorios'
    | '/_painel/sem-acesso'
    | '/_painel/pedidos/$id'
    | '/_painel/producao/$id'
    | '/_painel/pedidos/'
    | '/_painel/producao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel': {
      id: '/_painel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel/atrasos': {
      id: '/_painel/atrasos'
      path: '/atrasos'
      fullPath: '/atrasos'
      preLoaderRoute: typeof PainelAtrasosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/cadastros': {
      id: '/_painel/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof PainelCadastrosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/compras': {
      id: '/_painel/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof PainelComprasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/configuracoes': {
      id: '/_painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/dashboard': {
      id: '/_painel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PainelDashboardRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/envase': {
      id: '/_painel/envase'
      path: '/envase'
      fullPath: '/envase'
      preLoaderRoute: typeof PainelEnvaseRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/estoque': {
      id: '/_painel/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof PainelEstoqueRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/manutencao': {
      id: '/_painel/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof PainelManutencaoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/perdas': {
      id: '/_painel/perdas'
      path: '/perdas'
      fullPath: '/perdas'
      preLoaderRoute: typeof PainelPerdasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/relatorios': {
      id: '/_painel/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof PainelRelatoriosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/sem-acesso': {
      id: '/_painel/sem-acesso'
      path: '/sem-acesso'
      fullPath: '/sem-acesso'
      preLoaderRoute: typeof PainelSemAcessoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/pedidos/': {
      id: '/_painel/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PainelPedidosIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/pedidos/$id': {
      id: '/_painel/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PainelPedidosIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/producao/': {
      id: '/_painel/producao/'
      path: '/producao'
      fullPath: '/producao/'
      preLoaderRoute: typeof PainelProducaoIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/producao/$id': {
      id: '/_painel/producao/$id'
      path: '/producao/$id'
      fullPath: '/producao/$id'
      preLoaderRoute: typeof PainelProducaoIdRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelAtrasosRoute: typeof PainelAtrasosRoute
  PainelCadastrosRoute: typeof PainelCadastrosRoute
  PainelComprasRoute: typeof PainelComprasRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelDashboardRoute: typeof PainelDashboardRoute
  PainelEnvaseRoute: typeof PainelEnvaseRoute
  PainelEstoqueRoute: typeof PainelEstoqueRoute
  PainelManutencaoRoute: typeof PainelManutencaoRoute
  PainelPerdasRoute: typeof PainelPerdasRoute
  PainelRelatoriosRoute: typeof PainelRelatoriosRoute
  PainelSemAcessoRoute: typeof PainelSemAcessoRoute
  PainelPedidosIdRoute: typeof PainelPedidosIdRoute
  PainelProducaoIdRoute: typeof PainelProducaoIdRoute
  PainelPedidosIndexRoute: typeof PainelPedidosIndexRoute
  PainelProducaoIndexRoute: typeof PainelProducaoIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAtrasosRoute: PainelAtrasosRoute,
  PainelCadastrosRoute: PainelCadastrosRoute,
  PainelComprasRoute: PainelComprasRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelDashboardRoute: PainelDashboardRoute,
  PainelEnvaseRoute: PainelEnvaseRoute,
  PainelEstoqueRoute: PainelEstoqueRoute,
  PainelManutencaoRoute: PainelManutencaoRoute,
  PainelPerdasRoute: PainelPerdasRoute,
  PainelRelatoriosRoute: PainelRelatoriosRoute,
  PainelSemAcessoRoute: PainelSemAcessoRoute,
  PainelPedidosIdRoute: PainelPedidosIdRoute,
  PainelProducaoIdRoute: PainelProducaoIdRoute,
  PainelPedidosIndexRoute: PainelPedidosIndexRoute,
  PainelProducaoIndexRoute: PainelProducaoIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
